version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/blazor-wasm/weatherFrontEnd"
    schedule:
      interval: "daily"
    target-branch: "master"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "master"
    
  - package-ecosystem: "pip"
    directory: "/django"
    schedule:
      interval: "daily"
    target-branch: "master"
