# Generated by Django 3.2.8 on 2021-10-22 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City', models.CharField(max_length=64)),
                ('State', models.CharField(choices=[('DC', 'District of Columbia'), ('AL', 'Alabama'), ('MT', 'Montana'), ('AK', 'Alaska'), ('NE', 'Nebraska'), ('AZ', 'Arizona'), ('NV', 'Nevada'), ('AR', 'Arkansas'), ('NH', 'New Hampshire'), ('CA', 'California'), ('NJ', 'New Jersey'), ('CO', 'Colorado'), ('NM', 'New Mexico'), ('CT', 'Connecticut'), ('NY', 'New York'), ('DE', 'Delaware'), ('NC', 'North Carolina'), ('FL', 'Florida'), ('ND', 'North Dakota'), ('GA', 'Georgia'), ('OH', 'Ohio'), ('HI', 'Hawaii'), ('OK', 'Oklahoma'), ('ID', 'Idaho'), ('OR', 'Oregon'), ('IL', 'Illinois'), ('PA', 'Pennsylvania'), ('IN', 'Indiana'), ('RI', 'Rhode Island'), ('IA', 'Iowa'), ('SC', 'South Carolina'), ('KS', 'Kansas'), ('SD', 'South Dakota'), ('KY', 'Kentucky'), ('TN', 'Tennessee'), ('LA', 'Louisiana'), ('TX', 'Texas'), ('ME', 'Maine'), ('UT', 'Utah'), ('MD', 'Maryland'), ('VT', 'Vermont'), ('MA', 'Massachusetts'), ('VA', 'Virginia'), ('MI', 'Michigan'), ('WA', 'Washington'), ('MN', 'Minnesota'), ('WV', 'West Virginia'), ('MS', 'Mississippi'), ('WI', 'Wisconsin'), ('MO', 'Missouri'), ('WY', 'Wyoming'), ('PR', 'Puerto Rico')], max_length=2)),
                ('Latitude', models.DecimalField(decimal_places=4, max_digits=6)),
                ('Longitude', models.DecimalField(decimal_places=4, max_digits=7)),
            ],
        ),
        migrations.AddConstraint(
            model_name='locations',
            constraint=models.UniqueConstraint(fields=('City', 'State'), name='Unique City, ST'),
        ),
        migrations.AddConstraint(
            model_name='locations',
            constraint=models.UniqueConstraint(fields=('Latitude', 'Longitude'), name='Unique Location'),
        ),
    ]
