# Generated by Django 3.2.7 on 2021-12-01 00:57

from django.db import migrations, models
import django.utils.timezone
import wBE_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('measurement', models.CharField(blank=True, choices=[('SI', 'SI'), ('US', 'US')], max_length=16)),
                ('defaultPage', models.CharField(blank=True, choices=[('Hourly', 'Hourly'), ('Daily', 'Daily'), ('Account', 'Account')], max_length=16)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', wBE_app.models.AccountManager()),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City', models.CharField(max_length=64)),
                ('State', models.CharField(choices=[('DC', 'District of Columbia'), ('AL', 'Alabama'), ('MT', 'Montana'), ('AK', 'Alaska'), ('NE', 'Nebraska'), ('AZ', 'Arizona'), ('NV', 'Nevada'), ('AR', 'Arkansas'), ('NH', 'New Hampshire'), ('CA', 'California'), ('NJ', 'New Jersey'), ('CO', 'Colorado'), ('NM', 'New Mexico'), ('CT', 'Connecticut'), ('NY', 'New York'), ('DE', 'Delaware'), ('NC', 'North Carolina'), ('FL', 'Florida'), ('ND', 'North Dakota'), ('GA', 'Georgia'), ('OH', 'Ohio'), ('HI', 'Hawaii'), ('OK', 'Oklahoma'), ('ID', 'Idaho'), ('OR', 'Oregon'), ('IL', 'Illinois'), ('PA', 'Pennsylvania'), ('IN', 'Indiana'), ('RI', 'Rhode Island'), ('IA', 'Iowa'), ('SC', 'South Carolina'), ('KS', 'Kansas'), ('SD', 'South Dakota'), ('KY', 'Kentucky'), ('TN', 'Tennessee'), ('LA', 'Louisiana'), ('TX', 'Texas'), ('ME', 'Maine'), ('UT', 'Utah'), ('MD', 'Maryland'), ('VT', 'Vermont'), ('MA', 'Massachusetts'), ('VA', 'Virginia'), ('MI', 'Michigan'), ('WA', 'Washington'), ('MN', 'Minnesota'), ('WV', 'West Virginia'), ('MS', 'Mississippi'), ('WI', 'Wisconsin'), ('MO', 'Missouri'), ('WY', 'Wyoming'), ('PR', 'Puerto Rico')], max_length=2)),
                ('Latitude', models.DecimalField(decimal_places=4, max_digits=6)),
                ('Longitude', models.DecimalField(decimal_places=4, max_digits=7)),
            ],
        ),
        migrations.AddConstraint(
            model_name='locations',
            constraint=models.UniqueConstraint(fields=('City', 'State'), name='Unique City, ST'),
        ),
        migrations.AddConstraint(
            model_name='locations',
            constraint=models.UniqueConstraint(fields=('Latitude', 'Longitude'), name='Unique Location'),
        ),
        migrations.AddField(
            model_name='account',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='account',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
