# Generated by Django 3.2.7 on 2021-12-02 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wBE_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='defaultPage',
            field=models.CharField(blank=True, choices=[('Hourly', 'Hourly'), ('Daily', 'Daily'), ('Account', 'Account'), ('', '')], max_length=16),
        ),
        migrations.AlterField(
            model_name='account',
            name='measurement',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('US', 'US'), ('', '')], max_length=16),
        ),
    ]
